package edu.gcu.cst339.lab2_chinook_api.invoiceline;

import java.net.URI;
import java.util.List;

import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;

@Tag(name = "Invoice Lines", description = "The Invoice Line API")
@RestController
@RequestMapping("/api/invoice-lines")
class InvoiceLineController {
    
    private final InvoiceLineService invoiceLineService;
    
    InvoiceLineController(InvoiceLineService invoiceLineService) {
        this.invoiceLineService = invoiceLineService;
    }

    @Operation(summary = "Get all invoice lines", description = "Returns a list of all invoice lines")
    @ApiResponse(responseCode = "200", description = "Successfully retrieved list of invoice lines")
    @GetMapping
    List<InvoiceLineDto> getAll() {
        return invoiceLineService.findAll();
    }

    @Operation(summary = "Get invoice line by ID", description = "Returns a single invoice line by its ID")
    @ApiResponse(responseCode = "200", description = "Successfully retrieved invoice line")
    @ApiResponse(responseCode = "404", description = "Invoice line not found")
    @GetMapping("/{id}")
    ResponseEntity<InvoiceLineDto> getById(@PathVariable Integer id) {
        InvoiceLineDto invoiceLineDto = invoiceLineService.findById(id);
        return ResponseEntity.ok(invoiceLineDto);
    }

    @Operation(summary = "Create a new invoice line", description = "Creates a new invoice line and returns the created invoice line. The invoiceLineId is generated by the database; omit it from the request.")
    @ApiResponse(responseCode = "201", description = "Invoice line created successfully")
    @ApiResponse(responseCode = "400", description = "Invalid input data")
    @ApiResponse(responseCode = "409", description = "Conflict: invoiceId or trackId does not exist")
    @PostMapping
    ResponseEntity<InvoiceLineDto> create(@Valid @RequestBody InvoiceLineDto invoiceLineDto) {
        InvoiceLineDto createdInvoiceLine = invoiceLineService.create(invoiceLineDto);
        return ResponseEntity.created(URI.create("/api/invoice-lines/" + createdInvoiceLine.invoiceLineId())).body(createdInvoiceLine);
    }

    @Operation(summary = "Update an invoice line", description = "Updates an existing invoice line and returns the updated invoice line. The ID comes from the URL; any invoiceLineId in the body is ignored.")
    @ApiResponse(responseCode = "200", description = "Invoice line updated successfully")
    @ApiResponse(responseCode = "400", description = "Invalid input data")
    @ApiResponse(responseCode = "404", description = "Invoice line not found")
    @ApiResponse(responseCode = "409", description = "Conflict: invoiceId or trackId does not exist")
    @PutMapping("/{id}")
    ResponseEntity<InvoiceLineDto> update(@PathVariable Integer id, @Valid @RequestBody InvoiceLineDto invoiceLineDto) {
        InvoiceLineDto updatedInvoiceLine = invoiceLineService.update(id, invoiceLineDto);
        return ResponseEntity.ok(updatedInvoiceLine);
    }

    @Operation(summary = "Delete an invoice line", description = "Deletes an existing invoice line by its ID")
    @ApiResponse(responseCode = "204", description = "Invoice line deleted successfully")
    @ApiResponse(responseCode = "404", description = "Invoice line not found")
    @DeleteMapping("/{id}")
    ResponseEntity<Void> delete(@PathVariable Integer id) {
        invoiceLineService.delete(id);
        return ResponseEntity.noContent().build();
    }

    @ExceptionHandler(DataIntegrityViolationException.class)
    ResponseEntity<String> handleDataIntegrityViolationException(DataIntegrityViolationException ex) {
        return ResponseEntity.status(HttpStatus.CONFLICT).body("Request conflicts with existing data: the invoiceId or trackId may not exist.");
    }
}
